`timescale 1ns / 1ps

module sim_snn_rgb;

  parameter STIM_NAME_LEN = 256;
  parameter RESP_NAME_LEN = 256;
  
  parameter CLK_PERIOD    = 10;

  reg [8*STIM_NAME_LEN-1:0] stimuli_filename;
  reg [8*RESP_NAME_LEN-1:0] response_filename;

  integer x_blank = 100;     
  integer trail   = 1000;    

  reg         clk;
  reg         reset_n;
  reg  [2:0]  enable_in;
  
  reg         vs_in;
  reg         hs_in;
  reg         de_in;
  
  reg  [7:0]  r_in;
  reg  [7:0]  g_in;
  reg  [7:0]  b_in;

  wire        vs_out;
  wire        hs_out;
  wire        de_out;
  wire [7:0]  r_out;
  wire [7:0]  g_out;
  wire [7:0]  b_out;
  wire        clk_o;
  wire [2:0]  led;

  integer x_size;
  integer y_size;
  
  integer end_tb    = 0;
  integer mismatch = 0;

  always # (CLK_PERIOD / 2 ) clk = ~clk;

  snn_rgb duv  (
    .clk       (clk),
    .reset_n   (reset_n),
    .enable_in (enable_in),
    
    .vs_in     (vs_in),
    .hs_in     (hs_in),
    .de_in     (de_in),
    
    .r_in      (r_in),
    .g_in      (g_in),
    .b_in      (b_in),
    
    .vs_out    (vs_out),
    .hs_out    (hs_out),
    .de_out    (de_out),
    
    .r_out     (r_out),
    .g_out     (g_out),
    .b_out     (b_out),
    
    .clk_o     (clk_o),
    .led       (led)
  );

  integer stimuli_file;
  integer x, y;
  integer i;
  integer r_integer, g_integer, b_integer;
    
  reg [1023:0] line;
  
  initial begin

    stimuli_filename  = "/media/nisitha/My_Passport/MOODLE/Vivado_projects/Spiking-Neural-Network-on-FPGA-main/SNN-RGB/SNN-RGB.sim/sim_1/behav/xsim/test10.ppm";
    response_filename = "/media/nisitha/My_Passport/MOODLE/Vivado_projects/SNN_project/snn_implementation/results_img_dir/test10_snn_out_verilog.ppm";

    stimuli_file = $fopen(stimuli_filename, "r");
    
    if (stimuli_file == 0) begin
      $display("ERROR: could not open stimuli file");
      $finish;
    end

    $fgets(line, stimuli_file);     
    $fgets(line, stimuli_file);     
    $fgets(line, stimuli_file);  
       
    $sscanf(line, "%d %d", x_size, y_size);
    
    $fgets(line, stimuli_file);   
    
    clk       = 1'b0; 
    
    reset_n   = 1'b0;
    enable_in = 3'b111;
    
    vs_in     = 1'b0;
    hs_in     = 1'b0;
    de_in     = 1'b0;
    
    r_in      = 8'd0;
    g_in      = 8'd0;
    b_in      = 8'd0;

    # (CLK_PERIOD * 5);
    reset_n   = 1'b1;

    # (CLK_PERIOD * 10);

    for (y = 0; y < y_size; y = y + 1) begin

      if (y == 0)
        vs_in = 1'b1;
      else
        vs_in = 1'b0;

      hs_in = 1'b1;
      
      for (x = 0; x < x_blank; x = x + 1)
        @(negedge clk);
      hs_in = 1'b0;

      de_in = 1'b1;
      for (x = 0; x < x_size; x = x + 1) begin

        if ($feof(stimuli_file))
          $finish;

        $fscanf(stimuli_file, "%d %d %d", r_integer, g_integer, b_integer);

        r_in = r_integer[7:0];
        g_in = g_integer[7:0];
        b_in = b_integer[7:0];

        @(negedge clk);
        
      end

      de_in = 1'b0;
      
      r_in  = 8'd0;
      g_in  = 8'd0;
      b_in  = 8'd0;

    end

    for (i = 0; i < trail; i = i + 1)
      @(negedge clk);

    end_tb = 1;
    $fclose(stimuli_file);

    #20;
    $display("Simulation completed");
    $finish;

  end

  integer response_file;
  integer r_sim; 
  integer g_sim;
  integer b_sim;
  
  initial begin

    wait (hs_out == 1'b1);

    response_file = $fopen(response_filename, "w");
    
    if (response_file == 0) begin
      $display("ERROR: could not open response file");
      $finish;
    end

    $fdisplay(response_file, "P3");
    $fdisplay(response_file, "# generated by Verilog testbench");
    $fdisplay(response_file, "%0d %0d", x_size, y_size);
    $fdisplay(response_file, "255");

    while (end_tb != 1) begin
      @(negedge clk);
      if (de_out == 1'b1) begin

        r_sim = r_out;
        g_sim = g_out;
        b_sim = b_out;

        $fdisplay(response_file, "%0d %0d %0d", r_sim, g_sim, b_sim);
      end
    end

    $fclose(response_file);
    
    wait (end_tb == 2);

  end

endmodule
